#include "moves.h"
//lista de moves feita novamente no chat seguindo modelos do jogo
//Divisão de ataque fisico, especial e status (gen5)
//eles serão escolhidos aleatoriamente de acordo com o tipo do pokemon (ou talvez posso fazer o jogador escolher)
//no começo eu pensei em adicionar os efeitos de cada movimento (ex: self-destruct explode o usuário) mas não vai dar.
std::vector<Move> moveList = {
    Move("Tackle", "Normal", 40, 100, "Fisico"),
    Move("Scratch", "Normal", 40, 100, "Fisico"),
    Move("Quick Attack", "Normal", 40, 100, "Fisico"),
    Move("Hyper Fang", "Normal", 80, 90, "Fisico"),
    Move("Double-Edge", "Normal", 120, 100, "Fisico"),
    Move("Take Down", "Normal", 90, 85, "Fisico"),
    Move("Ember", "Fire", 40, 100, "Especial"),
    Move("Flamethrower", "Fire", 90, 100, "Especial"),
    Move("Fire Blast", "Fire", 110, 85, "Especial"),
    Move("Fire Punch", "Fire", 75, 100, "Fisico"),
    Move("Heat Wave", "Fire", 95, 90, "Especial"),
    Move("Burn Up", "Fire", 130, 100, "Especial"),
    Move("Water Gun", "Water", 40, 100, "Especial"),
    Move("Bubble Beam", "Water", 65, 100, "Especial"),
    Move("Surf", "Water", 90, 100, "Especial"),
    Move("Hydro Pump", "Water", 110, 80, "Especial"),
    Move("Aqua Jet", "Water", 40, 100, "Fisico"),
    Move("Waterfall", "Water", 80, 100, "Fisico"),
    Move("Thunder Shock", "Electric", 40, 100, "Especial"),
    Move("Thunderbolt", "Electric", 90, 100, "Especial"),
    Move("Thunder", "Electric", 110, 70, "Especial"),
    Move("Spark", "Electric", 65, 100, "Fisico"),
    Move("Thunder Punch", "Electric", 75, 100, "Fisico"),
    Move("Discharge", "Electric", 80, 100, "Especial"),
    Move("Vine Whip", "Grass", 45, 100, "Fisico"),
    Move("Razor Leaf", "Grass", 55, 95, "Fisico"),
    Move("Solar Beam", "Grass", 120, 100, "Especial"),
    Move("Leaf Blade", "Grass", 90, 100, "Fisico"),
    Move("Energy Ball", "Grass", 90, 100, "Especial"),
    Move("Giga Drain", "Grass", 75, 100, "Especial"),
    Move("Poison Sting", "Poison", 15, 100, "Fisico"),
    Move("Sludge", "Poison", 65, 100, "Especial"),
    Move("Sludge Bomb", "Poison", 90, 100, "Especial"),
    Move("Poison Jab", "Poison", 80, 100, "Fisico"),
    Move("Acid", "Poison", 40, 100, "Especial"),
    Move("Gunk Shot", "Poison", 120, 80, "Fisico"),
    Move("Poison Powder", "Poison", 0, 75, "Status"),
    Move("Toxic", "Poison", 0, 90, "Status"),
    Move("Sleep Powder", "Grass", 0, 75, "Status"),
    Move("Stun Spore", "Grass", 0, 75, "Status"),
    Move("Will-O-Wisp", "Fire", 0, 85, "Status"),
    Move("Thunder Wave", "Electric", 0, 90, "Status"),
    Move("Confusion", "Psychic", 50, 100, "Especial"),
    Move("Psybeam", "Psychic", 65, 100, "Especial"),
    Move("Psychic", "Psychic", 90, 100, "Especial"),
    Move("Zen Headbutt", "Psychic", 80, 90, "Fisico"),
    Move("Psyshock", "Psychic", 80, 100, "Especial"),
    Move("Lick", "Ghost", 30, 100, "Fisico"),
    Move("Shadow Ball", "Ghost", 80, 100, "Especial"),
    Move("Shadow Claw", "Ghost", 70, 100, "Fisico"),
    Move("Night Shade", "Ghost", 0, 100, "Especial"),
    Move("Hex", "Ghost", 65, 100, "Especial"),
    Move("Astonish", "Ghost", 30, 100, "Fisico"),
    Move("Mud-Slap", "Ground", 20, 100, "Especial"),
    Move("Earthquake", "Ground", 100, 100, "Fisico"),
    Move("Earth Power", "Ground", 90, 100, "Especial"),
    Move("Bulldoze", "Ground", 60, 100, "Fisico"),
    Move("Dig", "Ground", 80, 100, "Fisico"),
    Move("Bone Rush", "Ground", 25, 90, "Fisico"),
    Move("Ice Beam", "Ice", 90, 100, "Especial"),
    Move("Blizzard", "Ice", 110, 70, "Especial"),
    Move("Icy Wind", "Ice", 55, 95, "Especial"),
    Move("Ice Punch", "Ice", 75, 100, "Fisico"),
    Move("Powder Snow", "Ice", 40, 100, "Especial"),
    Move("Aurora Beam", "Ice", 65, 100, "Especial"),
    Move("Peck", "Flying", 35, 100, "Fisico"),
    Move("Wing Attack", "Flying", 60, 100, "Fisico"),
    Move("Aerial Ace", "Flying", 60, 999, "Fisico"),
    Move("Air Slash", "Flying", 75, 95, "Especial"),
    Move("Drill Peck", "Flying", 80, 100, "Fisico"),
    Move("Hurricane", "Flying", 110, 70, "Especial"),
    Move("Double Kick", "Fighting", 30, 100, "Fisico"),
    Move("Karate Chop", "Fighting", 50, 100, "Fisico"),
    Move("Brick Break", "Fighting", 75, 100, "Fisico"),
    Move("Close Combat", "Fighting", 120, 100, "Fisico"),
    Move("Low Sweep", "Fighting", 65, 100, "Fisico"),
    Move("Mach Punch", "Fighting", 40, 100, "Fisico"),
    Move("Bite", "Dark", 60, 100, "Fisico"),
    Move("Crunch", "Dark", 80, 100, "Fisico"),
    Move("Dark Pulse", "Dark", 80, 100, "Especial"),
    Move("Faint Attack", "Dark", 60, 999, "Fisico"),
    Move("Snarl", "Dark", 55, 95, "Especial"),
    Move("Night Slash", "Dark", 70, 100, "Fisico"),
    Move("Dragon Rage", "Dragon", 0, 100, "Especial"),
    Move("Dragon Claw", "Dragon", 80, 100, "Fisico"),
    Move("Dragon Breath", "Dragon", 60, 100, "Especial"),
    Move("Outrage", "Dragon", 120, 100, "Fisico"),
    Move("Twister", "Dragon", 40, 100, "Especial"),
    Move("Draco Meteor", "Dragon", 130, 90, "Especial"),
    Move("Iron Tail", "Steel", 100, 75, "Fisico"),
    Move("Metal Claw", "Steel", 50, 95, "Fisico"),
    Move("Flash Cannon", "Steel", 80, 100, "Especial"),
    Move("Bullet Punch", "Steel", 40, 100, "Fisico"),
    Move("Mirror Shot", "Steel", 65, 85, "Especial"),
    Move("Magnet Bomb", "Steel", 60, 999, "Fisico"),
    Move("Play Rough", "Fairy", 90, 90, "Fisico"),
    Move("Disarming Voice", "Fairy", 40, 999, "Especial"),
    Move("Moonblast", "Fairy", 95, 100, "Especial"),
    Move("Draining Kiss", "Fairy", 50, 100, "Especial"),
    Move("Fairy Wind", "Fairy", 40, 100, "Especial"),
    Move("Dazzling Gleam", "Fairy", 80, 100, "Especial")
};
